name: Release

on:
  pull_request:
    branches: 
        - "main"
    types: [ closed ]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PKG Info
        id: pkg
        uses: jaywcjlove/github-action-package@main
        with:
          unset: scripts.prepare

      - name: Publish to Registry
        id: publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          