name: Release

on:
  pull_request:
    types: [ closed ]

jobs:
  release:
    if: github.event.pull_request.base.ref == 'dev' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: jaywcjlove/github-action-package@main
        with:
          unset: scripts.prepare

      - name: Publish to Registry
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: true
        