name: CI
on:
  push:
    branches:
      - "!main"
      - "*"
  pull_request:
    branches:
      - "dev"
      - "main"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
            version: 8
            run_install: false

      - name: Install Node 20.x
        uses: actions/setup-node@v4
        with:
            node-version: "20.x"
            cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Run Build
        run: pnpm build

      - name: Run Unit Tests
        run: pnpm test:ci
